version: '3.8'

services: 
  web: 
    build: . 
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code 
    ports:
      - 8000:8000
    depends_on:
      - db 
    environment:
      - "DJANGO_SECRET_KEY=$$2sq9)#^s45h4d!pl9b7vfjd0!dzq2+h9&w!*bbk8x19qam*2c"
      - "DJANGO_DEBUG=True"

  db: 
    image: postgres:11
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: 
